#!/bin/csh -f
set RUN = "/usr/bin/time /usr/local/bin/valgrind -q --dsymutil=yes"
set FILES = /Users/kevin/Programs/cs323/hw2/files
set ENC = "./encode"
set DEC = "./decode"
set EOUT  = /Users/kevin/Programs/cs323/hw2/tmp/lzw.e
set DOUT  = /Users/kevin/Programs/cs323/hw2/tmp/lzw.d

echo Testing flags with a.in and specialchars.in
foreach flag ("" "-m 1" "-m 8" "-m 9" "-m 23 -e" "-m 24" "-m 25" "-m 50 -m 10")
	foreach file (a.in specialchars.in)
		echo Testing $file with flags set to $flag
		echo Encoding
		$RUN $ENC $flag < $FILES/$file > $EOUT
		echo Decoding
		$RUN $DEC < $EOUT | cmp - $FILES/$file
		#cmp ./encode.log ./decode.log
	end
end
echo Finished testing flags
echo



# encode < FILE | decode | cmp - FILE

#onintr cleanup
#cleanup:
#/bin/rm -rf $ARKIV
